# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

#cloud-config
users:
  - name: packer
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    packer:builder
  expire: False
ssh_pwauth: True
